In [4]:
import numpy as np
import scipy.io
import pandas as pd
import matplotlib.pyplot as plt
import pickle

In [5]:
path = './GLM/act/act_c_test.pickle'
path2 = './GLM/act/act_MOTOR.pickle'
path3 = './GLM/act/act_u_test.pickle'

In [7]:
pickle_in = open(path,"rb")
c_test = pickle.load(pickle_in)

pickle_in = open(path2,"rb")
motor = pickle.load(pickle_in)

pickle_in = open(path3,"rb")
u_test = pickle.load(pickle_in)

In [10]:
motor = motor[0]

In [16]:
motor

array([[0., 1., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 1., 0., 0., 0.],
       ...,
       [1., 0., 1., 0., 1.],
       [1., 1., 1., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [18]:
c_test = abs(c_test)

In [20]:
c_test

array([[0, 1, 0, 0, 1],
       [0, 0, 0, 1, 0],
       [1, 1, 1, 0, 0],
       ...,
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0]])

In [32]:
np.corrcoef(motor[:,0],u_test[:,0])

array([[1.        , 0.05136365],
       [0.05136365, 1.        ]])

In [2]:
activation_path = './GLM/activations/activation_SOCIAL.pickle'
beta_path = './GLM/betas/betas_SOCIAL.pickle'
truth_path = './Data/beta_truth/Beta_tfMRI_SOCIAL_LR_Glasser360.mat'

In [3]:
activation = np.load(activation_path, allow_pickle = True)
beta = np.load(beta_path, allow_pickle = True)
truth = scipy.io.loadmat(truth_path)
truth = truth['Beta']
truth = np.swapaxes(truth, 2, 0)

FileNotFoundError: [Errno 2] No such file or directory: './GLM/activations/activation_SOCIAL.pickle'

In [ ]:
truth[0,0,:]

In [ ]:
beta.shape

In [ ]:
truth.shape

In [ ]:
beta[0,0,:]

In [ ]:
activation[0,1,:]

In [ ]:
m, n, r = beta.shape
arr = np.column_stack((np.repeat(np.arange(m),n),beta.reshape(-1, beta.shape[-1])))
df = pd.DataFrame(arr)
df.rename(columns={df.columns[0]: "subject" }, inplace=True)

In [ ]:
df

In [ ]:
df[1].hist()

In [ ]:
m, n, r = truth.shape
arr = np.column_stack((np.repeat(np.arange(m),n),truth.reshape(-1, truth.shape[-1])))
df_t = pd.DataFrame(arr)
df_t.rename(columns={df_t.columns[0]: "subject" }, inplace=True)

In [ ]:
df_t

In [ ]:
df_t[1].hist()

In [ ]:
new = df.merge(df_t, left_index = True, right_index = True)

In [ ]:
plt.scatter(new['1_x'], new['1_y'], marker = '.', s = .5)

In [ ]:
plt.scatter(new['2_x'], new['2_y'], marker = '.', s = .5)

In [ ]:
plt.scatter(new['3_x'], new['3_y'], marker = '.', s = .5)

In [ ]:
plt.boxplot(df[df['subject'] == 0][1]-df_t[df_t['subject'] == 0][1])
plt.show

In [ ]:
df[1].corr(df_t[1])